Clarify refine.ini comments - fixes #3204
OpenRefine/OpenRefine pull request #3206
Opened 2020-09-23 01:16 UTC by tfmorris

Fixes #3204 

Clarifies comments for:
- Google Data OAuth config
- JVM heap

NOTE: Our current JVM max heap settings are *lowering* the size computed for the default on my machine (4096 MB => 1400 MB), so we may just want to accept the defaults unless the user specifically wants to override them.

2020-09-23 01:32 UTC, thadguidry requested changes

2020-09-23 01:32 UTC, thadguidry commented on refine.ini
> +# (NOTE: This are only needed for developers. Users of released versions can ignore this)
```suggestion
# (NOTE: These GDATA settings are only needed for developers. Users of released versions can ignore this)
```

2020-09-23 05:42 UTC, wetneb commented
Periodic note that this release process is flaky: our Google credentials will get deactivated one day because we are not supposed to ship them to users, even in a vaguely hidden way.

2020-09-23 05:43 UTC, wetneb approved these changes

2020-09-25 15:29 UTC, tfmorris commented on refine.ini
> +# (NOTE: This are only needed for developers. Users of released versions can ignore this)
Fixed subject verb agreement

2020-09-25 15:30 UTC, merged