Add Security Policy on how we handle reports
OpenRefine/OpenRefine pull request #3405
Opened 2020-12-12 21:55 UTC by thadguidry

2020-12-13 07:10 UTC, wetneb requested changes
Thanks for looking into this! In general, projects try to keep security vulnerabilities secret until a new version is released with a fix. So I think we should not encourage people to report these on GitHub directly, but rather to a restricted mailing list (openrefine-coredev, if posting from non-subscribers is allowed? Otherwise, we could create a new mailing list for that purpose).

2020-12-13 07:10 UTC, wetneb commented on SECURITY.md
> +| < 3.3   | :x:                |
```suggestion
| <= 3.3   | :x:                |
```

2020-12-13 18:48 UTC, thadguidry commented
@wetneb Yes, GitHub does have that security option for secret reporting.  I'll change that and point it to the openrefine-coredev mailing list.  I also had the same question and concerned but thought I'd start with this simple template as they suggest and then get the coredev team's feedback.  Let me update this...

2021-02-28 02:53 UTC, tfmorris approved these changes

2021-03-03 10:32 UTC, wetneb approved these changes

2021-03-03 10:33 UTC, merged