Add feature to trigger a button on hitting Enter to fix #3137
OpenRefine/OpenRefine pull request #3406
Opened 2020-12-13 17:13 UTC by leoshrey

Fixes #3137 

- Pressing "Enter" in the project name field at the preview stage will now create the project.

check it out

![sample123 (1)](https://user-images.githubusercontent.com/53581274/102018571-16171e00-3d94-11eb-8565-7688a78056ba.gif)

2020-12-13 17:54 UTC, wetneb requested changes
Thanks a lot, much cleaner!

I think it would be better to make sure the field and the button are both part of the same `<form>` element, with the event listener being bound to the form submission event rather than the click on the button. This would directly ensure that the form gets submitted when the user presses "Enter", and would probably be more accessible too.

2020-12-13 20:57 UTC, leoshrey commented
Agreed and I think it’s a great idea as this event of triggering a button makes less sense than directly submitting the form by pressing Enter only, it will probably increase the accessibility as well as speed.
I am working on it.

2020-12-14 20:11 UTC, leoshrey commented
Hi @wetneb , I tried to bind the event listener with the form submission event rather than clicking on the button.
But as I found that this way of submitting the form requires form id attribute value, to which either I am not able to locate through or there isn't any. I also tried creating the <form> tag by providing useful attributes there and wrote the JS code for event listener using those attributes, but after doing so whenever I press Enter to Project Name input field it redirects me to the previous page (where we import the project). 
Can you please guide me to the form id value or should we proceed using .click() method instead ?

2020-12-14 20:43 UTC, wetneb commented
If the input and button are not yet enclosed in a `<form>`, then you should be able to add one, and add an `id` so that you are able to locate it in the Javascript code.

2020-12-15 12:24 UTC, leoshrey commented
I tried enclosing:
1. Input and button in <form>
2. All html elements in <form>
and writing JS for the same for submit event with event listener.
But both of the times whenever I press Enter key I am redirecting to the previous page (project import page).

In case 1. I am only redirecting to previous page without any extra warning log (checked in console).
In case 2. I am redirecting to the previous page as well as I am getting one extra warning as "Form submission canceled because the form is not connected".
Looks like .submit() event is not working because of browser version.
What are your views ?

2020-12-15 12:50 UTC, wetneb commented
Does your submit event handler cancel the default action with `e.preventDefault()`?

2020-12-15 13:11 UTC, leoshrey commented
No, I am not using this method.
Although I tried it both ways but the result is same.

2020-12-15 14:26 UTC, wetneb commented
You could try to follow this example:
https://github.com/OpenRefine/OpenRefine/blob/79eac0b8113f295c48b7152461e373beb0433e43/extensions/wikidata/module/scripts/dialogs/manage-account-dialog.js#L174
https://github.com/OpenRefine/OpenRefine/blob/79eac0b8113f295c48b7152461e373beb0433e43/extensions/wikidata/module/scripts/dialogs/password-login-dialog.html#L15

2020-12-26 19:42 UTC, leoshrey commented
Hey @wetneb, changes made as requested https://github.com/OpenRefine/OpenRefine/pull/3406#pullrequestreview-550943567. 

- Now the same event is bound as with createButton to keep it standard.

2020-12-26 20:20 UTC, wetneb commented on main/webapp/modules/core/scripts/index/default-importing-controller/parsing-panel.js
> +  document.getElementById("projectNameTextField").addEventListener("keyup", function (event) {
This still uses a keyup event listener, we should use a submit event instead.

2021-01-27 08:58 UTC, wetneb commented
Hi @leoshrey, do you still intend to work on this?

2021-01-27 11:37 UTC, leoshrey commented
https://github.com/OpenRefine/OpenRefine/pull/3406#issuecomment-768137725 Yes, I am working on this. I was just busy with something for the past few days. Now, back in flow.

2021-04-14 21:20 UTC, wetneb commented
@leoshrey I am closing this PR to clear up our backlog. If you want to keep working on this do not hesitate to open a new PR. Thanks!

2021-04-14 21:20 UTC, closed without merging