fix-test-and-hyperlinks
OpenRefine/OpenRefine pull request #3591
Opened 2021-02-07 11:45 UTC by singhakshita

for the PR #3588 for the issue #2519

1.initially  "https://www.wikidata.org/wiki/Property:P670 https://www.wikidata.org/wiki/Property:P669 are now mapped to https://schema.org/streetAddress via https://www.wikidata.org/wiki/Property:P2235 " was not treated as a link ,now each text component inside it is treated as text and each link is uniquely identified.
2. tests added to check if links inside of text snippets are treated as hrefs.

2021-02-07 16:46 UTC, singhakshita commented
@wetneb  this is the pull request of #3588  ,if i run prettier check ,then will pass all the PR tests ,but then it would increase the number of changes but making changes in all test.spec.js ,so can you please tell me what i should do ?

2021-02-08 00:16 UTC, tfmorris requested changes
Looking good. One small functional change and a few formatting changes needed. I didn't mark all instances of the code style issues, so please just follow the patterns wherever they apply e.g. multiline `else` to `} else {`

2021-02-08 00:16 UTC, tfmorris commented on main/webapp/modules/core/scripts/views/data-table/cell-ui.js
> +      for( var i=0;i<arr.length;i++){
```suggestion
      for (var i=0; i<arr.length; i++) {
```
Until we adopt a new coding style for our Javascript, let's match the current style for code added to an existing module

2021-02-08 00:16 UTC, tfmorris commented on main/webapp/modules/core/scripts/views/data-table/cell-ui.js
> +    else{
```suggestion
    } else {
```

2021-02-08 00:16 UTC, tfmorris commented on main/webapp/modules/core/scripts/views/data-table/cell-ui.js
> +          if(spanArr.length !=0 ){
```suggestion
          if (spanArr.length != 0) {
```

2021-02-08 02:08 UTC, singhakshita commented on main/webapp/modules/core/scripts/views/data-table/cell-ui.js
> +        if(URL.looksLikeUrl(arr[i])){
here looksLikeURL doesn't use regex  (back in util.js it uses normal new url()  ) ,

2021-02-08 05:22 UTC, closed without merging

2021-02-08 05:25 UTC, singhakshita commented
due to many conflict issues and large number of diffrences added to due to eslint and pretteier i am not able to commit changes in this branch so i am  pushings another PR