common transform toBoolean added
OpenRefine/OpenRefine pull request #3622
Opened 2021-02-12 09:36 UTC by singhakshita

fixes #3518  , changes all the cell data that doesn't match with "true" as false . similar to what the "edit" shown on each cell does when "to boolean" option is chosen.
<img width="558" alt="Screenshot 2021-02-12 at 1 41 26 PM" src="https://user-images.githubusercontent.com/52077474/107751773-d6dd5d00-6d43-11eb-868d-ac3926e887dc.png">
<img width="468" alt="Screenshot 2021-02-12 at 1 41 41 PM" src="https://user-images.githubusercontent.com/52077474/107751792-dc3aa780-6d43-11eb-89f5-cc5dc0efaea9.png">

2021-02-12 11:10 UTC, wetneb requested changes
I don't think `if(value != 'true' , 'false' , 'true')` is the expression we want here. It should return a boolean, not a string. I would expect something such as `value == 'true'` (without the surrounding `if` statement). Perhaps with an additional tweak to handle null values, depending on what we want to do with them.

2021-02-12 13:03 UTC, singhakshita commented
@wetneb  yeah of course it had to be boolean data ,sorry my bad ! updated

2021-02-12 13:50 UTC, wetneb approved these changes
That works for me, but I would like to leave the opportunity to @ostephens to comment about how nulls should be handled here: should this convert nulls to `false` or keep them as null values?

2021-03-01 11:02 UTC, singhakshita commented
<img width="556" alt="Screenshot 2021-03-01 at 4 25 30 PM" src="https://user-images.githubusercontent.com/52077474/109488176-390bc100-7aab-11eb-95ce-d4155eb9943d.png">
<img width="339" alt="Screenshot 2021-03-01 at 4 24 54 PM" src="https://user-images.githubusercontent.com/52077474/109488184-3ad58480-7aab-11eb-9726-0057ea04c1ce.png">

i have added a submenu to choose the language ,for now javascript sql and python , (now the data is being transformed to true or false based truthy values as documented in that particular language.
please let me know if it works well

2021-03-03 11:59 UTC, wetneb reviewed
I like it! I think this adds more value than the previous proposal. A few things:
* I would expect the menu labels to be translatable (so, using `$.i18n`)
* In English we should keep consistent casing: use "Python **t**ruthy **v**alues", not "Python Truthy Values".

It would still be nice to have more comments from others about how useful these transforms would be (@thadguidry perhaps?), but since this has been open for a while I think we can also merge this if no one else chimes in.

2021-03-03 12:49 UTC, wetneb commented
Ah sorry I didn't see the discussion on the linked issue. It looks like people have legitimate concerns about adding those.

2021-04-14 21:19 UTC, wetneb commented
@singhakshita unfortunately I think we need to close this PR - sorry for the work you invested into it! We should have checked the discussion on the related issue more carefully.

2021-04-14 21:19 UTC, closed without merging