fixed issue #3363
OpenRefine/OpenRefine pull request #3884
Opened 2021-05-07 12:38 UTC by pvcodes

Fixes #3363 

Changes proposed in this pull request:
- Capitalization is to be done in Sentence case

2021-05-07 13:11 UTC, ostephens requested changes
Thanks for this @pvcodes. Unfortunately it looks like you have applied quite a general change across these strings rather than checking if each string needs changing.

You can see I've commented on some of the changes - but every line you've changed in this document needs checking in this way to make sure you haven't removed uppercase letters that are correct.

2021-05-07 15:40 UTC, pvcodes commented on main/webapp/modules/core/langs/translation-en.json
> +    "core-index-create/formats": "Tsv, csv, *sv, excel (.xls and .xlsx), json, xml, rdf as xml, and google data documents are all supported. support for other formats can be added with openrefine ext
I'll fix it, but need some time!

2021-05-30 11:55 UTC, pvcodes commented
I've fixed more of the things. Have a look

2021-05-30 13:46 UTC, wetneb commented
Personally I would only review this once @ostephens' comments above have been addressed.

2021-05-31 11:30 UTC, pvcodes commented
@wetneb I have added more commits after that :)

2021-05-31 12:57 UTC, wetneb commented
Maybe, but they don't seem to address the comments Owen brought up, do they? Otherwise the review comments would be marked as "Outdated" in GitHub I think.

2021-09-23 09:51 UTC, wetneb commented
Closing this per inactivity.

2021-09-23 09:51 UTC, closed without merging