Fixed issue #3674
OpenRefine/OpenRefine pull request #3885
Opened 2021-05-07 13:01 UTC by pvcodes

Fixes #3674 

Changes proposed in this pull request:
- Links were sort of broken, but not that much

2021-05-07 13:44 UTC, ostephens requested changes
Thanks. Unfortunately these aren't quite the changes that are needed to address #3674 . Please see the comment from @joanneong in that issue to understand the corrections that need to be made

2021-05-07 15:43 UTC, pvcodes commented on docs/docs/manual/expressions.md
> +*   [find](grelfunctions#find-and-replace)
Got it!

2021-05-09 06:38 UTC, wetneb commented
Hi @pvcodes and @ostephens, it seems to me that this issue was actually resolved by #3821 already. Sorry that I did not find this issue and close it when I did that! So I would say this PR should only be used to fix the anchor parts of links (which can still be broken because that isn't validated by the CI at the moment unfortunately).

2021-05-30 20:36 UTC, wetneb commented
Closing in favour of #3920

2021-05-30 20:36 UTC, closed without merging