Add explicit anchor ids in docs
OpenRefine/OpenRefine pull request #3891
Opened 2021-05-09 07:05 UTC by wetneb

Fixes #3888.

As a preparation for #3890.

2021-05-16 18:28 UTC, wetneb commented
Merging soon unless people have concerns :)

2021-05-22 20:21 UTC, thadguidry requested changes
@wetneb I've reviewed all 65 files thoroughly.  Added suggested improvements.

2021-05-22 20:21 UTC, thadguidry commented on docs/docs/manual/grel.md
> +#### isBlank(e), isNonBlank(e), isNull(e), isNotNull(e), isNumeric(e), isError(e) {#isblanke-isnonblanke-isnulle-isnotnulle-isnumerice-iserrore}
```suggestion
#### isBlank(e), isNonBlank(e), isNull(e), isNotNull(e), isNumeric(e), isError(e) {#isblank}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/docs/manual/grel.md
> +#### forNonBlank(e, v, eNonBlank, eBlank) {#fornonblanke-v-enonblank-eblank}
```suggestion
#### forNonBlank(e, v, eNonBlank, eBlank) {#fornonblank}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/docs/manual/grel.md
> +#### forRange(n from, n to, n step, v, e) {#forrangen-from-n-to-n-step-v-e}
```suggestion
#### forRange(n from, n to, n step, v, e) {#forrange}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/docs/manual/grel.md
> +#### forEachIndex(e1, i, v, e2) {#foreachindexe1-i-v-e2}
```suggestion
#### forEachIndex(e1, i, v, e2) {#foreachindex}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/docs/manual/grel.md
> +#### forEach(e1, v, e2) {#foreache1-v-e2}
```suggestion
#### forEach(e1, v, e2) {#foreach}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/docs/manual/grel.md
> +#### filter(e1, v, e test) {#filtere1-v-e-test}
```suggestion
#### filter(e1, v, e test) {#filter}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/docs/manual/grel.md
> +#### with(e1, variable v, e2) {#withe1-variable-v-e2}
```suggestion
#### with(e1, variable v, e2) {#with}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/manual/installing.md
> +#### Using openrefine.exe {#using-openrefineexe}
```suggestion
#### Using openrefine.exe {#using-openrefine-exe}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/manual/installing.md
> +#### Using refine.bat {#using-refinebat}
```suggestion
#### Using refine.bat {#using-refine-bat}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/manual/running.md
> +#### With openrefine.exe {#with-openrefineexe}
```suggestion
#### With openrefine.exe {#with-openrefine-exe}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/manual/running.md
> +#### With refine.bat {#with-refinebat}
```suggestion
#### With refine.bat {#with-refine-bat}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/manual/running.md
> +### History (Undo/Redo) {#history-undoredo}
```suggestion
### History (Undo/Redo) {#history-undo-redo}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/manual/sortview.md
> +### Show/hide “null” {#showhide-null}
```suggestion
### Show/hide “null” {#show-hide-null}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/manual/transposing.md
> +## Columnize by key/value columns {#columnize-by-keyvalue-columns}
```suggestion
## Columnize by key/value columns {#columnize-by-key-value-columns}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/manual/troubleshooting.md
> +### If you’re having a problem: {#if-youre-having-a-problem}
```suggestion
### If you are having a problem: {#if-you-are-having-a-problem}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/technical-reference/build-test-run.md
> +## Building, Testing and Running OpenRefine from IntelliJ idea {#building-testing-and-running-openrefine-from-intellij-idea}
```suggestion
## Building, Testing and Running OpenRefine from IntelliJ IDEA {#building-testing-and-running-openrefine-from-intellij-idea}
```
Capitalize

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/technical-reference/development-roadmap.md
> +### 4.0 {#40}
```suggestion
### 4.0 {#4-0}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/technical-reference/functional-tests.md
> +### 1. Install Cypress {#1-install-cypress}
```suggestion
### 1. Install Cypress {#install-cypress}
```
Remove ordinals

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/technical-reference/functional-tests.md
> +### 2. Start the test runner {#2-start-the-test-runner}
```suggestion
### 2. Start the test runner {#start-the-test-runner}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/technical-reference/functional-tests.md
> +### 3. Run the existing tests {#3-run-the-existing-tests}
```suggestion
### 3. Run the existing tests {#run-the-existing-tests}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/technical-reference/functional-tests.md
> +### 4. Add your first test {#4-add-your-first-test}
```suggestion
### 4. Add your first test {#add-your-first-test}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/technical-reference/functional-tests.md
> +#### Overriding with a cypress.env.json file {#overriding-with-a-cypressenvjson-file}
```suggestion
#### Overriding with a cypress.env.json file {#overriding-with-a-cypress-env-json-file}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/technical-reference/functional-tests.md
> +## CI/CD {#cicd}
```suggestion
## CI/CD {#ci-cd}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/technical-reference/translating.md
> +## User entry of language data ## {#user-entry-of-language-data-}
```suggestion
## User entry of language data ## {#user-entry-of-language-data}
```
remove hanging dashes

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/technical-reference/translating.md
> +### Simple case of localized string ### {#simple-case-of-localized-string-}
```suggestion
### Simple case of localized string ### {#simple-case-of-localized-string}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/technical-reference/translating.md
> +### Localization with a parameterized value ### {#localization-with-a-parameterized-value-}
```suggestion
### Localization with a parameterized value ### {#localization-with-a-parameterized-value}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/technical-reference/translating.md
> +### Localization with a singular/plural value ### {#localization-with-a-singularplural-value-}
```suggestion
### Localization with a singular/plural value ### {#localization-with-a-singular-plural-value}
```

2021-05-22 20:21 UTC, thadguidry commented on docs/versioned_docs/version-3.4/technical-reference/translating.md
> +## Server / Backend Coding {#server--backend-coding}
```suggestion
## Server / Backend Coding {#server-backend-coding}
```
remove extra dash

2021-05-24 10:47 UTC, ostephens commented on docs/docs/manual/grel.md
> +#### if(e, eTrue, eFalse) {#ife-etrue-efalse}
We've already got these ids out there - I know I've used them in my documentation and posted on forums etc. Unless there is some benefit to changing the IDs I think we should keep as is

2021-05-24 10:48 UTC, ostephens commented on docs/docs/manual/installing.md
> +#### Using openrefine.exe {#using-openrefineexe}
As above - I think there needs to be some benefit to changing the IDs because we could be breaking links that are already out there

2021-05-24 10:48 UTC, ostephens commented on docs/docs/manual/installing.md
> +#### Using refine.bat {#using-refinebat}
As above - I think there needs to be some benefit to changing the IDs because we could be breaking links that are already out there

2021-05-24 10:48 UTC, ostephens commented on docs/docs/manual/running.md
> +#### With openrefine.exe {#with-openrefineexe}
As above - I think there needs to be some benefit to changing the IDs because we could be breaking links that are already out there

2021-05-24 10:48 UTC, ostephens commented on docs/docs/manual/running.md
> +#### With refine.bat {#with-refinebat}
As above - I think there needs to be some benefit to changing the IDs because we could be breaking links that are already out there

2021-05-24 12:07 UTC, thadguidry commented on docs/docs/manual/grel.md
> +#### if(e, eTrue, eFalse) {#ife-etrue-efalse}
@ostephens Ah, ok.

2021-05-25 12:54 UTC, wetneb commented
Thanks Thad for the in-depth review! I have not thought much about whether we should stick to the automatically generated anchor ids or if it is better to prettify them.

I guess it is fine to tweak them, but have you checked if the ones you changed were linked to anywhere? We would need to update the corresponding links then.

2021-05-25 13:28 UTC, thadguidry commented
@wetneb I checked and did find links, but I did not also update those links.  (There were only a few, mostly in each same doc file referenced)

2021-05-25 18:29 UTC, wetneb commented
Then I'd say let's just do those changes in another PR, which simultaneously changes the anchors *and* updates the links, otherwise the docs will be broken in the meantime.

2021-05-26 04:48 UTC, merged