Migrate content from MediaWiki bot page on wiki to user manual
OpenRefine/OpenRefine pull request #4652
Opened 2022-03-28 21:25 UTC by khadijm

Fixes #3575

2022-03-28 21:27 UTC, khadijm commented
preview 
![Screenshot from 2022-03-28 22-14-32](https://user-images.githubusercontent.com/88087734/160490063-6c39522e-3083-4068-828d-d6faa15a0896.png)

![Screenshot from 2022-03-28 22-14-49](https://user-images.githubusercontent.com/88087734/160490083-73030fd5-6b76-492e-823f-422ced3bdad8.png)

please @wetneb  and @ostephens  can you review my PR  thanks

2022-03-29 07:56 UTC, wetneb reviewed
Thank you! The content you added seems largely redundant with the lines before (lines 88 to 97). Perhaps it would be better to rework those and make them applicable to other Wikibase instances than Wikidata?

2022-03-29 07:56 UTC, wetneb commented on docs/docs/manual/wikibase/overview.md
> +Official manual of bot passwords: https://www.mediawiki.org/wiki/Manual:Bot_passwords
I would rather avoid adding a URL in plain text like this (rather create a hyperlink with a meaningful label).

2022-03-29 07:56 UTC, wetneb commented on docs/docs/manual/wikibase/overview.md
> +1. Goto https://www.mediawiki.org/wiki/Special:BotPasswords.
`Goto` should be `Go to`

2022-04-02 08:36 UTC, khadijm commented
new preview 
![Screenshot from 2022-04-02 09-34-41](https://user-images.githubusercontent.com/88087734/161374870-fd31266d-3d6f-414d-8d6f-ea6214dbf8e7.png)

2022-04-02 11:51 UTC, wetneb reviewed
I still see a lot of redundancy between your additions and the contents of the previous section, for instance lines 89 to 91 duplicate your line 113.

2022-04-05 07:50 UTC, khadijm commented
please @wetneb  can you check again if there is still redundancy. thanks

2022-04-05 08:09 UTC, wetneb commented
I am not so sure about this change: the part that you removed also covers normal passwords that are not mentioned in your "bot password" section.

2022-04-14 05:31 UTC, khadijm commented
yep

2022-04-22 16:17 UTC, wetneb requested changes
There is still the same redundancy of content I mentioned earlier.

2022-04-25 05:44 UTC, wetneb commented
I would like to close this PR soon because it does not look like it is getting in a mergeable state.

2022-05-26 11:56 UTC, closed without merging