made clustering method document skimmable
OpenRefine/OpenRefine pull request #4718
Opened 2022-04-08 09:40 UTC by Babi-B

Fixes #{issue number here}

Changes proposed in this pull request:
- makes clustering method documentation more skimmable for superficial readers

2022-04-08 09:50 UTC, Babi-B commented
> I'm not 100% sure what you are proposing when you say you could
>
> >make the [clustering-methods](https://docs.openrefine.org/manual/cellediting#clustering-methods) document for the end-users more skimmable
>
>I don't know if you can explain here before doing the work or if it's easier to make a PR for the docs and get feedback on that - I'd be happy either way

@ostephens @antoine2711. 

I thought perhaps it would be good to edit the content of the document so superficial readers could easily sieve through for what they want.

2022-04-08 10:04 UTC, Babi-B commented
@WaltonG thanks.  Missed that

2022-04-10 16:16 UTC, wetneb commented
Looking at the preview at https://deploy-preview-4718--openrefine-docs.netlify.app/next/manual/cellediting#cluster-and-edit, it looks fine to me, although I am not really sure what is the problem with [the original](https://docs.openrefine.org/next/manual/cellediting#cluster-and-edit) to be honest.

However the new version has an inconsistency in the hierarchy of headings, with the following list of subparts:
1. Fingerprinting
2. N-gram fingerprinting
3. Metaphone3 fingeprinting
4. …

The problem is that 1. is not a fingerprinting method on its own (rather an intro to the general technique of fingerprinting), so it should not be at the same hierarchical level as specific fingerprinting methods.

Also the indentation of the new version looks a bit off, perhaps because these numbered sub-headings are not actually meant to be used like that, but are more for enumerated lists?

2022-04-10 16:27 UTC, Babi-B commented
Ok @wetneb. So would you advice that I update the file to correct the inconsistencies or should I discard the changes all together?

2022-04-10 21:08 UTC, antoine2711 commented
> Looking at the preview at https://deploy-preview-4718--openrefine-docs.netlify.app/next/manual/cellediting#cluster-and-edit, it looks fine to me, although I am not really sure what is the problem with [the original](https://docs.openrefine.org/next/manual/cellediting#cluster-and-edit) to be honest.

@wetneb: I would tend to disagree here.
![image](https://user-images.githubusercontent.com/12217525/162639755-3c3bf776-e3b4-4435-b19f-a7878c2fd96f.png)

In this image, Phonetic clustering is a section title, and yet, it's smaller than the next title, a sub-section of it. So the inconsistancy you spotted in @Babi-B works was already there.

Also, why does the Baider-Morse section doesn't get it paragraph? There is a paragraph break missing there.

As a bonus, I would put links to the relevant section in the summary above.
Cleaning the hierarchy and putting links would be, in my opinion, « making the doc more skimmable ».

Regards, Antoine

2022-04-10 21:17 UTC, Babi-B commented
Ok @antoine2711 . Thanks

2022-04-10 22:07 UTC, antoine2711 commented on docs/docs/manual/cellediting.md
> +The clustering pop-up window offers you a variety of clustering methods; 6 different key collision clustering methods and 2 nearest neighbour clustering methods.
```suggestion
The clustering pop-up window offers you two categories of clustering methods: 6 different key collision clustering methods and 2 nearest neighbour clustering methods.
```

2022-04-13 08:51 UTC, wetneb commented
This PR adds two files, [docs/docs/manual/img.png](https://github.com/OpenRefine/OpenRefine/pull/4718/files#diff-9389edea530131d27b5867fa4b213432159d85e3f54089a4388c9b847cdcee08) und docs/docs/manual/img_1.png, but I cannot figure out why they are there. Should they be removed?

@antoine2711 can I leave it to you review and merge this?

2022-04-14 10:05 UTC, antoine2711 reviewed
I think we are getting there. Is there a reason you deleted the summary? I think it helps to browse them.

Regards, Antoine

2022-04-15 07:55 UTC, antoine2711 requested changes
I like this. Only 2 small details.

Regards, Antoine

2022-04-15 07:55 UTC, antoine2711 commented on docs/docs/manual/cellediting.md
> +- [Key collision](#key-collision)
```suggestion
- [Key Collision](#key-collision)
```

Could you capitalise every summary items? Like the title there are below. There is more than 10 that could be capitalized from what I saw.

2022-04-15 07:55 UTC, antoine2711 commented on docs/docs/manual/cellediting.md
>  ##### Phonetic clustering {#phonetic-clustering}
```suggestion
_**Phonetic clustering {#phonetic-clustering}**_
```

Here, we have a complicated problem. The Header level 4 is much smaller than the paragraph title. So, could we put it the same size, but in italic? It's really an informative header…

2022-04-15 10:06 UTC, antoine2711 approved these changes

2022-04-15 10:06 UTC, merged

2022-04-15 10:07 UTC, antoine2711 commented
Good work! One more done, @Babi-B. 

Best Regards, Antoine