Issue 4103 lineimporter custom delimiter
OpenRefine/OpenRefine pull request #5434
Opened 2022-11-14 00:09 UTC by EgorDm

Fixes #4103

Changes proposed in this pull request:
- LineBasedImporter now uses Scanner with regex delimiter instead of a LineNumberReader
- Updated UI to select between newline splitting (default) and regex-based splitting.
- Added tests for basic LineBasedImporter functionality and regex splitting

2022-11-16 21:32 UTC, wetneb approved these changes
Amazing, thank you so much @EgorDm!
I tested it and it works flawlessly. The code and tests look perfect too.
Thumbs up on my side! Merging soon unless anyone has concerns.

2022-11-16 23:02 UTC, tfmorris requested changes
Thanks for the contribution! Just a few cosmetic issues to clean up.

2022-11-16 23:02 UTC, tfmorris commented on main/tests/server/src/com/google/refine/importers/LineBasedImporterTests.java
> +import static org.testng.Assert.assertEquals;
This static import is never used. All the `Assert.assertEquals` mentions can be changed to just `assertEquals`

2022-11-16 23:02 UTC, tfmorris commented on main/tests/server/src/com/google/refine/importers/LineBasedImporterTests.java
> +import com.google.refine.util.ParsingUtilities;
This import is unused. It and the other unused imports should be removed.

2022-11-16 23:04 UTC, tfmorris commented on main/src/com/google/refine/importers/LineBasedImporter.java
> +        } catch (Exception e) {
Actually, on further investigation, this code doesn't throw any exceptions at all! The entire try/catch block should be removed.

2022-11-16 23:29 UTC, EgorDm commented on main/src/com/google/refine/importers/LineBasedImporter.java
> +        } catch (Exception e) {
Thanks for the review.

Good call. 
Scanner seems to catch IO errors and put them in a member variable. 
I have removed try catch and added the following block.

```
if (lnReader.ioException() != null) {
            logger.error("Error reading line-based file", lnReader.ioException());
        }
```

2022-11-16 23:30 UTC, EgorDm commented on main/tests/server/src/com/google/refine/importers/LineBasedImporterTests.java
> +Copyright 2010,2011 Google Inc.
Should be fixed in the latest commit.

2022-11-17 19:32 UTC, tfmorris approved these changes
LGTM Thanks for the updates!

2022-11-17 19:48 UTC, merged