Waiting screen while guessing reconciliation types should be internal to the reconciliation dialog #4877
OpenRefine/OpenRefine pull request #5722
Opened 2023-03-22 23:13 UTC by ayushrai206

Fixes #4877 

Changes proposed in this pull request:
- adds the loading message and the spinner to the types container

2023-03-23 07:19 UTC, wetneb commented
Really nice @ayushrai206! It works pretty well! One suggestion I would still have is that the panel on the right, where we can map columns to properties, could be displayed without waiting for the types to be guessed. You can see in this screencast that this panel is initially blank while the types are fetched, and intuitively that should not be needed.
![recon](https://user-images.githubusercontent.com/309908/227131148-4dd94735-e154-49d1-b830-c373560b2745.gif)

2023-03-23 09:26 UTC, Abbe98 requested changes
This looks very good! I only have a minor suggestion.

It would also be nice if it was possible to see and interact with the "columns to properties" column while loading is still happening as suggested by @wetneb.

2023-03-23 20:11 UTC, Abbe98 commented on main/webapp/modules/core/scripts/util/dialog.js
> +DialogSystem.showBusyReconciling = function(message) {
I would also move it from the `DialogSystem` object into `self`.

2023-03-23 20:41 UTC, ayushrai206 commented on main/webapp/modules/core/scripts/util/dialog.js
> +DialogSystem.showBusyReconciling = function(message) {
@Abbe98 i have also tried to bring back the panel on the right,please have a look

2023-03-23 21:58 UTC, Abbe98 requested changes
Functionality vise it appears to work flawlessly. ⭐  Just a minor change request left from my end.

2023-03-24 02:18 UTC, ayushrai206 commented on main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js
> +DialogSystem.showBusyReconciling = function(message) {
did it @Abbe98

2023-03-24 08:02 UTC, merged