gives preference to user if they want to automatch or not
OpenRefine/OpenRefine pull request #5733
Opened 2023-03-26 15:13 UTC by ayushrai206

Fixes #4722 

Changes proposed in this pull request:
- gives preference to user if they want to automatch candidates with high confidence or not, keeping it true by default .

2023-03-27 13:26 UTC, Abbe98 requested changes
This only appears to be true by default because that is set in the HTML, meanwhile the new code does not interact with the `checked` attribute so it does not seem to have the intended effect.

2023-03-27 13:26 UTC, Abbe98 commented on main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js
> -        autoMatch: this._elmts.automatchCheck[0].checked,
This should remain as it just gets the value of "checked" from the DOM?

2023-03-27 13:26 UTC, Abbe98 commented on main/webapp/modules/core/scripts/reconciliation/standard-service-panel.js
> +  this._elmts.automatchCheck[0]=JSON.parse(Refine.getPreference("ui.reconciliation.automatch", true));
I expect this to still set the `checked` attribute.

2023-03-28 18:15 UTC, Abbe98 approved these changes
Nicely done!

2023-03-28 18:16 UTC, merged

2023-03-28 19:18 UTC, wetneb commented
done by https://github.com/OpenRefine/openrefine.org/pull/209

2023-03-28 19:33 UTC, ayushrai206 commented
> Could it be possible to have an accompanying documentation update? Otherwise users are unlikely to discover it.
yes, working on it.

2023-03-28 19:40 UTC, antoine2711 commented
@ayushrai206 : @Abbe98 took care of it. Check the previous comment by @wetneb.

Thank you very much for your work and congrat for this achievement.

Best Regards, Antoine

2023-03-29 04:18 UTC, Abbe98 commented
Sorry! I already had a draft...

On Tue, Mar 28, 2023 at 9:40 PM Antoine Beaubien ***@***.***>
wrote:

> @ayushrai206 <https://github.com/ayushrai206> : @Abbe98
> <https://github.com/Abbe98> took care of it. Check the previous comment
> by @wetneb <https://github.com/wetneb>.
>
> Thank you very much for your work and congrat for this achievement.
>
> Best Regards, Antoine
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OpenRefine/OpenRefine/pull/5733#issuecomment-1487496263>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAUCQJ3RNCPZ6DIHHJRIRQTW6M5C5ANCNFSM6AAAAAAWIHUY2Y>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>