Remove Datejs and Moment.js dependencies
OpenRefine/OpenRefine pull request #6169
Opened 2023-11-17 06:26 UTC by elebitzero

Changes proposed in this pull request:
  - Change formatting of dates in Open Project table to use Intl.DateFormat instead of Moment.js.
   - Formatting is the same except OR now uses 12-hour time format with AM/PM vs 24-hour time format with AM/PM which was incorrect.
  - Webapp package.json
    - Remove datejs-coolite (Unused after https://github.com/OpenRefine/OpenRefine/pull/6157).
    - Remove Moment.js (Deprecated https://momentjs.com/).
    
(Moment.js - using 24HR time with AM/PM)
![image](https://github.com/OpenRefine/OpenRefine/assets/42903164/4d078e57-09b0-44be-8dfa-ce3551b8c086)

(Intl.DateFormat overriding default formatting to match the existing hardcoded format: YYYY-MM-DD MM:HH AM)
![image](https://github.com/OpenRefine/OpenRefine/assets/42903164/5b22d2c0-ef45-45ef-887d-61852bb23606)

2023-11-17 20:48 UTC, tfmorris requested changes
This is great! The current implementation is clearly wrong. I never noticed that before.

Rather than switching to a different, slightly better, fixed format, I suggest that we punt the entire problem to the internationalization package. This will use 24 hour clock in the UK and AM/PM in the U.S., let the Arabic users read their dates & times from right to left, etc. It gets us out of the business of date & time formatting altogether.

2023-11-17 20:48 UTC, tfmorris commented on main/webapp/modules/core/scripts/index/open-project-ui.js
> +const timeFormatter =  new Intl.DateTimeFormat(navigator.language, timeOptions);
```suggestion
const options = { dateStyle: 'medium', timeStyle: 'medium' };
const dateFormatter = new Intl.DateTimeFormat(navigator.language, options);
```

2023-11-17 20:48 UTC, tfmorris commented on main/webapp/modules/core/scripts/index/open-project-ui.js
> +      project.date = `${year}-${month}-${day} ${hour}:${minute} ${dayPeriod}`;
```suggestion
      project.date = dateFormatter.format(date);
```

I suggest we let the internationalization code do *all* of the formatting

2023-11-17 22:46 UTC, elebitzero commented
@tfmorris

I initially used the default formatting based on user's language. For 'en-US' that resulted in '11/15/2023, 09:43 PM'.

Because the timestamps are sortable, it makes sense to use a hardcoded datetime format which orders the elements from large to small, e.g. YYYY MM DD HH MM. While thinking about it further today, I realize that is why they used military time also.

So, I have updated the PR to keep the hardcoded formatting, except remove the AM/PM, which is not supported by Intl.DateFormat when 24-hour format is selected.


- '2023-11-15 12:50 PM'  current
- '11/15/2023, 09:43 PM'  (Intl.Dateformat default for 'en-US' language
- '2023-11-15 12:50' PR  

If you really think that the datetime should be formatted per user's language, then please file another issue so it can be discussed.

2023-11-18 16:34 UTC, tfmorris commented
OK, I created #6172. It looks like it couple be as simple as prepending a hidden span with a timestamp (or the current ISO 8601 date) which could form the basis of the sorting.

2023-11-18 16:34 UTC, tfmorris approved these changes

2023-11-19 01:26 UTC, tfmorris commented
I've put up #6173 which can be reviewed once this PR is merged.

2023-11-19 07:19 UTC, merged

2023-11-20 02:41 UTC, tfmorris commented
@Abbe98 since you gave a thumb's up to the internationalization idea, you might be interested in reviewing #6173. For some reason I'm unable to request you as a reviewer on the PR.