Issue #2000 added --noproxy 127.0.0.0.1 to curl
OpenRefine/OpenRefine pull request #6361
Opened 2024-02-13 09:36 UTC by tejasbhosale17

Fixes #{2000}
Issue #2000

2024-02-13 19:54 UTC, wetneb requested changes
Thank you! The issue mentions that a similar adaptation should be done for downloads done via `wget`. Could you also take care of that? According to the manual it should be enough to define a `no_proxy=127.0.0.1` environment variable.

2024-02-14 02:43 UTC, tejasbhosale17 commented
Yes Sure. I made similar changes for wget please review.

2024-02-14 07:07 UTC, wetneb commented on refine
> +        wget --noproxy 127.0.0.1 -O - $URL > /dev/null 2>&1
No, the same syntax does not work for wget, as `--noproxy` is not a valid wget option.

2024-02-14 09:30 UTC, wetneb commented on refine
> +        wget --no-proxy -q -O - $URL_LOCAL > /dev/null 2>&1
```suggestion
        no_proxy=127.0.0.1 wget -O - $URL_LOCAL > /dev/null 2>&1
```

2024-02-14 09:30 UTC, wetneb commented on refine
> +            RUNNING=`wget --no-proxy -q -O - $URL_LOCAL | grep "$CHECK_STR"`
```suggestion
            RUNNING=`no_proxy=127.0.0.1 wget -O - $URL_LOCAL | grep "$CHECK_STR"`
```

2024-02-15 11:29 UTC, tejasbhosale17 commented
@wetneb I made the suggested changes, please let me know if I need to follow any steps since this is my first open-source contribution.

2024-02-15 12:25 UTC, wetneb approved these changes
Thank you!

2024-02-16 16:01 UTC, merged