tests: Clean up unnecessary try-catch blocks
OpenRefine/OpenRefine pull request #6645
Opened 2024-05-28 14:12 UTC by wetneb

Closes #6644.

2024-05-28 19:25 UTC, tfmorris commented
Was this done with the help of an IDE's refactoring tools? Trying to figure out how much attention I need to pay to the voluminous changes...

2024-05-28 19:36 UTC, wetneb commented
No, I had to do most of it manually. If you know of a technique to automate something like this, I am interested. I thought about recipes from OpenRewrite but they don't seem to have any (the closest I could find was [normalizing the `throws` statements in tests](https://docs.openrewrite.org/recipes/java/testing/cleanup/simplifytestthrows)) and I didn't feel like writing one (they make it rather hard to run their tool locally to push people to their cloud service, which discourages me from investing in it).

If you find it a good use of your time to scrutinize all of it, I would recommend doing it with a diff tool like [difftastic](https://github.com/Wilfred/difftastic) because it gives a much clearer picture.

2024-07-02 21:54 UTC, tfmorris requested changes
Thanks for all the test cleanup. That was a lot of work!

My eyes were kind of glazing over by the end, but hopefully I caught the bulk of the issues. All in all things look good with just a few minor improvements needed. It'll be a nice simplification of the tests.

2024-07-02 21:54 UTC, tfmorris commented on main/tests/server/src/com/google/refine/importers/XmlImportUtilitiesTests.java
> +        inputStream = new ByteArrayInputStream(xml.getBytes("UTF-8"));
```suggestion
        inputStream = new ByteArrayInputStream(xml.getBytes(StandardCharsets.UTF_8));
```

2024-07-02 21:54 UTC, tfmorris commented on main/tests/server/src/com/google/refine/importers/XmlImportUtilitiesTests.java
> +    public void loadData(String xml) throws Exception {
```suggestion
    public void loadData(String xml) {
```

2024-07-02 21:54 UTC, tfmorris commented on main/tests/server/src/com/google/refine/importers/XmlImportUtilitiesTests.java
> +    public void ParserSkip() throws Exception {
I think for these low level helpers where they throw one or two  very specific exceptions, it's probably better to declare the actual exceptions thrown

```suggestion
    public void ParserSkip() throws TreeReaderException {
```

2024-07-02 21:54 UTC, tfmorris commented on main/tests/server/src/com/google/refine/importers/XmlImportUtilitiesTests.java
> +    public TreeReader createXmlParser() throws Exception {
```suggestion
    public TreeReader createXmlParser() throws IOException, XMLStreamException  {
```

2024-07-02 21:54 UTC, tfmorris commented on main/tests/server/src/com/google/refine/importers/XmlImportUtilitiesTests.java
> +    public void loadSampleJson() throws Exception {
This method appears to be unused, but it doesn't throw any exceptions.

```suggestion
    public void loadSampleJson() {
```

2024-07-02 21:54 UTC, tfmorris commented on main/tests/server/src/com/google/refine/importers/XmlImportUtilitiesTests.java
> +    public void loadSampleXml() throws Exception {
```suggestion
    public void loadSampleXml() {
```

Doesn't throw with the charset fix

2024-07-02 21:54 UTC, tfmorris commented on main/tests/server/src/com/google/refine/importers/XmlImporterTests.java
> +        inputStream = new ByteArrayInputStream(testString.getBytes("UTF-8"));
```suggestion
        inputStream = new ByteArrayInputStream(testString.getBytes(StandardCharsets.UTF_8));
```
Same pattern as JSON importer. Fix this and then undo all the added `throws` clauses up the call stack

2024-07-02 21:54 UTC, tfmorris commented on main/tests/server/src/com/google/refine/importers/XmlImporterTests.java
> +    private void RunTest(String testString, ObjectNode objectNode) throws Exception {
```suggestion
    private void RunTest(String testString, ObjectNode objectNode) {
```

2024-07-02 21:54 UTC, tfmorris commented on main/tests/server/src/com/google/refine/importers/XmlImporterTests.java
> +    private void RunTest(String testString) throws Exception {
```suggestion
    private void RunTest(String testString) {
```

2024-07-02 21:54 UTC, tfmorris commented on main/tests/server/src/com/google/refine/grel/GrelTests.java
> +            assertThrows(ParsingException.class, () -> MetaParser.parse("grel:" + test));
```suggestion
            assertThrows("Expression failed to generate parse syntax error: " + test, ParsingException.class, () -> MetaParser.parse("grel:" + test));
```
For loop based tests, it's valuable to know which iteration failed

2024-07-08 17:01 UTC, wetneb commented on main/tests/server/src/com/google/refine/commands/util/CancelProcessesCommandTests.java
> -            // expected
Indeed, it is caught and converted to an HTTP response with `{"code": "error", …}`, so I have updated the test to reflect that

2024-07-15 18:03 UTC, tfmorris approved these changes

2024-07-18 05:02 UTC, merged